### ISSUE TITLE
Bar Chart Metrics - Gaurav

### ISSUE THREAD

**Issue by singh-karanpal** [UBC-MDS/DSCI_532_group_201_milestone3_4_natural_disaster#14]
@sgauravm Can you check the metrics of bar chart from previous python app and new R app. They are slightly off (Just check with Jasmine if we are using some different data or same data). Now the death per event's scale is low.

Python App link:
https://natural-disaster-submission.herokuapp.com

RDash link:
https://natural-disaster-rdash.herokuapp.com

**Comment by sgauravm** [comment]
This is a bug in the python app. The metric used in that is wrong and I will fix it after this lab. The R calculations are correct. Thanks for identifying the bug.

**Comment by singh-karanpal** [comment]
Great! So, I will go ahead and close this now for this milestone!
