### ISSUE TITLE
Reflections - Jack

### ISSUE THREAD

**Issue by singh-karanpal** [UBC-MDS/DSCI_532_group_201_milestone3_4_natural_disaster#15]
There are few issues with R Dash, I have opened a new issue for that as well. Please use that information for reflections. We want to mention explicitly to TA so that they are aware of framework shortcomings.

**Check**: RDash Issues #12

**Comment by ghost** [comment]
Yes I will do! Thanks for pointing this out! Team work makes dreams work! :)

**Comment by singh-karanpal** [comment]
We can close this now, as we have updated reflections
