### ISSUE TITLE
Line Chart Default Data - Jasmine

### ISSUE THREAD

**Issue by singh-karanpal** [UBC-MDS/DSCI_532_group_201_milestone3_4_natural_disaster#17]
@jasmineqyj 

In tab 2, for line chart!
Can you please mention in the line **Please Select a Country** that Default is China.

It should looks something like this:

**Please Select a Country - Default (China)**

Then when user is selecting any country, this title is changing fine! :)

**Comment by jasmineqyj** [comment]
Line chart title fixed.
