### ISSUE TITLE
Modified proposal

### ISSUE THREAD

**Issue by sgauravm** [UBC-MDS/DSCI_532_group_201_milestone3_4_natural_disaster#4]
We need to create an updated proposal. We can copy paste the same proposal but we need to modify the latest changes that we made. Is anybody working on the proposal part and is it done?

**Comment by singh-karanpal** [comment]
I don't think we need to re-write our proposal because we are not changing our research questions and we are not changing our dataset. We are only changing the dashboards from Python to R.

**Comment by singh-karanpal** [comment]
Closing this issue too!
